events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;
        root /var/www/html/public;
        index index.php index.html;

        # Timeouts
        fastcgi_read_timeout 300;
        fastcgi_send_timeout 300;
        client_max_body_size 50M;

        # Assets Vue.js (js, css, images)
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
            expires max;
            log_not_found off;
            access_log off;
        }

        # Routes Laravel
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_read_timeout 300;
            include fastcgi_params;
        }
    }
}
